In [79]:
import pandas as pd
import numpy as np

# Data loading and initial assessment

In [80]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [81]:
df.shape

(891, 12)

In [82]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [83]:
df.isna().sum()/df.shape[0]*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [84]:
df.duplicated().sum()

0

In [85]:
df.info(memory_usage=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)

# Data cleaning

In [86]:
df.head(0)

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [87]:
for c in df.columns:
    print(f"{c}    :    {df[c].isna().sum()}    :    {df[c].nunique()}    :    {df[c].dtypes}")

PassengerId    :    0    :    891    :    int64
Survived    :    0    :    2    :    int64
Pclass    :    0    :    3    :    int64
Name    :    0    :    891    :    object
Sex    :    0    :    2    :    object
Age    :    177    :    88    :    float64
SibSp    :    0    :    7    :    int64
Parch    :    0    :    7    :    int64
Ticket    :    0    :    681    :    object
Fare    :    0    :    248    :    float64
Cabin    :    687    :    147    :    object
Embarked    :    2    :    3    :    object

In [88]:
df = df.drop(columns=['PassengerId','Cabin'])
df.shape

(891, 10)

In [89]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df.isna().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    2
dtype: int64

In [90]:
df['Embarked'] = df['Embarked'].fillna(df["Embarked"].mode()[0])
df.isna().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [91]:
for c in df.columns:
    print(f"{c}    :    {df[c].isna().sum()}    :    {df[c].nunique()}    :    {df[c].dtypes}")

Survived    :    0    :    2    :    int64
Pclass    :    0    :    3    :    int64
Name    :    0    :    891    :    object
Sex    :    0    :    2    :    object
Age    :    0    :    88    :    float64
SibSp    :    0    :    7    :    int64
Parch    :    0    :    7    :    int64
Ticket    :    0    :    681    :    object
Fare    :    0    :    248    :    float64
Embarked    :    0    :    3    :    object

In [92]:
df['Name'].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [93]:
df = df.drop(columns=['Name'])
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Embarked'],
      dtype='object')

In [94]:
for c in df.columns:
    print(f"{c}    :    {df[c].isna().sum()}    :    {df[c].nunique()}    :    {df[c].dtypes}")

Survived    :    0    :    2    :    int64
Pclass    :    0    :    3    :    int64
Sex    :    0    :    2    :    object
Age    :    0    :    88    :    float64
SibSp    :    0    :    7    :    int64
Parch    :    0    :    7    :    int64
Ticket    :    0    :    681    :    object
Fare    :    0    :    248    :    float64
Embarked    :    0    :    3    :    object

In [95]:
df['Ticket'].sample(20)

224              19943
724             113806
742           PC 17608
8               347742
35              113789
150        S.O.P. 1166
372             323951
563    SOTON/OQ 392082
162             347068
40                7546
602             113796
588              14973
829             113572
322             234818
825             368323
869             347742
249             244252
316             244367
494          A/4 45380
619              31028
Name: Ticket, dtype: object